Codebreaker console for RubyGarage
Turzhanskyi/console-codebreaker-rg pull request #1
Opened 2021-01-18 12:54 UTC by Turzhanskyi

Task details are [here](https://docs.google.com/document/d/1VW3Mk1W-pGkq0FadPih689_k971Zy8inzk6UCPHDLzs/edit)

2021-02-24 20:31 UTC, n1zx1 approved these changes

2021-02-25 19:16 UTC, zelenyid approved these changes
Looks good

2021-03-01 11:48 UTC, nico-saj requested changes

2021-03-01 11:48 UTC, nico-saj commented on lib/services/game_process.rb
> +      Codebreaker::Constants::LEVELS.each_key do |name|
`Codebreaker::Constants::LEVELS.each do |name, difficulty|`?

2021-03-01 11:48 UTC, nico-saj commented on lib/services/game_process.rb
> +      send(MAIN_MENU_COMMANDS[answer.to_sym])
What will happen if answer is not included in `MAIN_MENU_COMMANDS`?

2021-03-01 11:48 UTC, nico-saj commented on lib/services/game_process.rb
> +    MAIN_MENU_COMMANDS = { start: :start, rules: :rules, stats: :stats, exit: :exit }.freeze
Do u really need doubling commands in key and value? It's better to use array

2021-03-01 12:08 UTC, Turzhanskyi commented on lib/services/game_process.rb
> +      send(MAIN_MENU_COMMANDS[answer.to_sym])
We got message "'You have passed unexpected command. Please choose one from listed commands.'"
after it "Enter command to continue: [start|rules|stats|exit]"

puts ```message(:'errors.message.unexpected_command')``` from
```
module CodebreakerConsole::class Console

def main_menu
      message(:main_menu)
      answer = user_enter
      return process_answer_menu(answer) if MAIN_MENU_COMMANDS.include?(answer)

      message(:'errors.message.unexpected_command')
      main_menu
end
````

2021-03-01 21:37 UTC, Turzhanskyi commented on lib/services/game_process.rb
> +      Codebreaker::Constants::LEVELS.each_key do |name|
fixed

2021-03-01 21:37 UTC, Turzhanskyi commented on lib/services/game_process.rb
> +    MAIN_MENU_COMMANDS = { start: :start, rules: :rules, stats: :stats, exit: :exit }.freeze
fixed

2021-03-01 21:44 UTC, Turzhanskyi commented
@nico-saj  fixed. Please, review)

2021-03-02 12:40 UTC, nico-saj approved these changes

2021-04-08 05:58 UTC, merged